In [167]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [168]:
A = np.random.randint(0, 10, 50)

In [169]:
A

array([5, 2, 6, 0, 6, 7, 8, 5, 4, 8, 7, 6, 3, 3, 3, 4, 2, 3, 4, 2, 7, 3,
       1, 3, 9, 1, 5, 4, 0, 4, 9, 5, 8, 5, 9, 8, 7, 2, 5, 4, 3, 5, 7, 5,
       6, 6, 5, 5, 4, 3])

In [170]:
A.shape

(50,)

In [171]:
A.shape = (5, 10)

In [172]:
A.reshape(10, 5)

array([[5, 2, 6, 0, 6],
       [7, 8, 5, 4, 8],
       [7, 6, 3, 3, 3],
       [4, 2, 3, 4, 2],
       [7, 3, 1, 3, 9],
       [1, 5, 4, 0, 4],
       [9, 5, 8, 5, 9],
       [8, 7, 2, 5, 4],
       [3, 5, 7, 5, 6],
       [6, 5, 5, 4, 3]])

In [173]:
A = A.reshape(10, 5)

In [174]:
A

array([[5, 2, 6, 0, 6],
       [7, 8, 5, 4, 8],
       [7, 6, 3, 3, 3],
       [4, 2, 3, 4, 2],
       [7, 3, 1, 3, 9],
       [1, 5, 4, 0, 4],
       [9, 5, 8, 5, 9],
       [8, 7, 2, 5, 4],
       [3, 5, 7, 5, 6],
       [6, 5, 5, 4, 3]])

In [175]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [176]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [177]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [178]:
np.ones((8, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [179]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [180]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [181]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
np.diag(A)

array([1, 5, 9])