In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
grades = [35, 10, 1, 16]

In [43]:
curved = []

for g in grades:
    curved.append(g * 1.1)

In [44]:
curved2 = []

for g in curved:
    curved2.append(g + 4)

In [45]:
curved

[38.5, 11.0, 1.1, 17.6]

In [46]:
grad_arr = np.array(grades)

In [47]:
grad_arr * 1.2

array([42. , 12. ,  1.2, 19.2])

In [48]:
grades = np.array([85, 70, 80])
weights = np.array([.2, .35, .45])

In [49]:
wgrades = grades * weights

In [50]:
wgrades

array([17. , 24.5, 36. ])

In [51]:
wgrades.sum()

77.5

In [52]:
grades @ weights #dot product

77.5

In [53]:
grades = np.array([[85, 70, 80],
                 [12, 88, 77],
                 [85, 91, 33]])

In [54]:
grades * weights

array([[17.  , 24.5 , 36.  ],
       [ 2.4 , 30.8 , 34.65],
       [17.  , 31.85, 14.85]])

In [55]:
wgrades = grades * weights

In [56]:
wgrades

array([[17.  , 24.5 , 36.  ],
       [ 2.4 , 30.8 , 34.65],
       [17.  , 31.85, 14.85]])

In [57]:
wgrades.sum(axis = 1)

array([77.5 , 67.85, 63.7 ])

In [58]:
weights.shape

(3,)

In [59]:
weights.reshape(3, 1)

array([[0.2 ],
       [0.35],
       [0.45]])

In [60]:
grades @ weights.reshape(3, 1)

array([[77.5 ],
       [67.85],
       [63.7 ]])